#!/usr/bin/env node
/**
 * Embed a self-contained app document as a TypeScript asset module.
 *
 * Usage:
 *   node embed-app.mjs <index.html> <out.ts> <CONST_NAME>
 *
 * Example:
 *   node embed-app.mjs ~/Questions/.saddle/apps/my-app/index.html \
 *     /app/packages/client/ui-app-store/src/client/my-app.ts MY_APP_HTML
 *
 * Generating the module (rather than hand-escaping) matters: a 30 KB document with
 * quotes, backslashes and newlines is easy to corrupt by hand, and a corrupted
 * literal is what produces "Missing initializer in const declaration" at runtime.
 */
import { readFileSync, writeFileSync, statSync } from 'node:fs'

const [htmlPath, outPath, constName] = process.argv.slice(2)
if (!htmlPath || !outPath || !constName) {
  console.error('usage: node embed-app.mjs <index.html> <out.ts> <CONST_NAME>')
  process.exit(2)
}
if (!/^[A-Z][A-Z0-9_]*$/.test(constName)) {
  console.error(`const name should be SCREAMING_SNAKE_CASE, got: ${constName}`)
  process.exit(2)
}

const html = readFileSync(htmlPath, 'utf8')
const header = [
  '/**',
  ' * Generated by scripts/embed-app.mjs — do not edit by hand.',
  ' *',
  ` * The app is one self-contained HTML document (no imports, no build step, no`,
  ' * framework at runtime), so it is mounted in a sandboxed iframe and evaluated',
  ' * verbatim by the host: nothing here goes through the entry-module wrapper.',
  ' */',
  '',
  '',
].join('\n')

const module = `${header}export const ${constName}: string = ${JSON.stringify(html)}\n`
writeFileSync(outPath, module)

// Round-trip check: the literal must decode back to exactly the source bytes.
const literal = module.slice(module.indexOf('= ') + 2).trim()
const roundTripped = JSON.parse(literal)
const identical = roundTripped === html

console.log(`source     : ${htmlPath} (${html.length} chars, ${statSync(htmlPath).size} bytes)`)
console.log(`module     : ${outPath} (${statSync(outPath).size} bytes)`)
console.log(`round-trip : ${identical ? 'identical' : 'MISMATCH — do not ship'}`)
if (!identical) process.exit(1)
